"""IDs, die von Fortschrittcallbacks ausgegeben werden"""

ERIC_FORTSCHRITTCALLBACK_ID_EINLESEN = 10
ERIC_FORTSCHRITTCALLBACK_ID_VORBEREITEN = 20
ERIC_FORTSCHRITTCALLBACK_ID_VALIDIEREN = 30
ERIC_FORTSCHRITTCALLBACK_ID_SENDEN = 40
ERIC_FORTSCHRITTCALLBACK_ID_DRUCKEN = 50
